### ISSUE TITLE
Serial as key for disk instead of name

### ISSUE THREAD

**Issue by tobiasbp** [sdwilsh/py-freenas#3]
As the `name` for a disk can change (Like when rebooting or replacing disks), maybe it would be better to use the `serial` as the key.

**Comment by sdwilsh** [comment]
Hmm, yeah, that's a good point!  I will tackle that some time in the next few days, as it matters for my other project that depends on this, [sdwilsh/hass-freenas](https://github.com/sdwilsh/hass-freenas/)
