### ISSUE TITLE
Renaming of PyPI package to reflect access type

### ISSUE THREAD

**Issue by tobiasbp** [sdwilsh/py-freenas#4]
The FreeNAS API V2 is available two ways: [Websocket and RESTful](https://www.truenas.com/docs/hub/additional-topics/api/
).

Maybe the PyPI package could be renamed to something like `py-freenas-ws` (Or some other, funnier, "pythonic" name). If someone else comes along implementing the RESTful API, it would be nice for them to be able to use the name `py-freenas-rest`.

Just a thought.....

**Comment by sdwilsh** [comment]
It doesn't look like I can rename a package on pypi, alas.  With that said, I'm also not opposed to supporting both in this library either.  I choose the websockets, because it's what powers their UI and I figured it would be more likely to be supported longer-term, but having a swapped out backend with the same interface could be nice.

**Comment by tobiasbp** [comment]
Sounds like a good idea with support for both types. In that scenario there is no need to consider the naming I was contemplating.

However, [FreeNAS is going to be ranamed TrueNAS (Core)](https://www.ixsystems.com/blog/truenas-core-features/).

**Comment by tobiasbp** [comment]
Project could potentially involve to support both types of API. Closing.

**Comment by sdwilsh** [comment]
I am going to rename this, @tobiasbp.  After looking at a lot of other libraries out there, I think `aiotruenas-client` is probably best.

**Comment by tobiasbp** [comment]
Sounds good. Also, I have not given up on this. I'm just busy with other
things at work. Sorry.

**Comment by sdwilsh** [comment]
I haven't touched this in over a month for similar reasons, so no worries :D
