### ISSUE TITLE
Disks: Serial number weirdness?

### ISSUE THREAD

**Issue by tobiasbp** [sdwilsh/py-freenas#6]
When I'm pulling data on disks from a Freenas 11.2-U7 system, I get serials with trailing  white space??

```
 {'acousticlevel': 'DISABLED',
  'advpowermgmt': 'DISABLED',
  'description': '',
  'devname': 'da22',
  'enclosure_slot': None,
  'expiretime': None,
  'hddstandby': 'ALWAYS ON',
  'identifier': '{serial_lunid}8DH7VKWH            _5000cca253d1a9de',
  'multipath_member': '',
  'multipath_name': '',
  'name': 'da22',
  'number': 22,
  'passwd': '',
  'serial': '8DH7VKWH            ',
  'size': '12000138625024',
  'smartoptions': '',
  'subsystem': 'da',
  'togglesmart': True,
  'transfermode': 'Auto'},
```

Maybe we need to to use `str.trim()`? What kind of data do we get from other systems?

**Comment by sdwilsh** [comment]
Weird...mine does not have whitespace.  I imagine it's probably vendor-specific and set in the firmware.  Trim is likely fine, but leaving the spaces is also probably fine since it should still be unique.

**Comment by tobiasbp** [comment]
Yes, you are right. As it's still unique, it's not a problem.
