### ISSUE TITLE
Ability to load credentials from environment variables.

### ISSUE THREAD

**Issue by tobiasbp** [sdwilsh/py-freenas#7]
It would be convenient to be able to [load credentials from environment variables](https://docs.python.org/3/library/os.html#os.getenv). Handy when running containerized applications.

**Comment by sdwilsh** [comment]
Not sure if this library should do it.  I was thinking for my application, I was just going to do a light-weight wrapper around the `Machine` class to handle something like this.  It'd be pretty trivial do something like this as a client:
```python
class EnvMachine(Machine):
    @staticmethod
    async def create():
        super().create(username=os.getenv("API_USER"), password=os.getenv("API_PASSWORD"))
```

**Comment by tobiasbp** [comment]
You are right. In my mind, I guess I was implementing my use case, and not working on the wrapper. Sorry.
